// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAiMRDtDECyt_Rj2x9Eac6NvktWJm5DdXA',
    appId: '1:372475938876:web:dcea4ad904ce78c1d09b39',
    messagingSenderId: '372475938876',
    projectId: 'flows-eac79',
    authDomain: 'flows-eac79.firebaseapp.com',
    databaseURL: 'https://flows-eac79-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flows-eac79.appspot.com',
    measurementId: 'G-QMHCDCL1WF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDX88zij_nHVEIvSD8EU7u94at3DYwtQ0',
    appId: '1:372475938876:android:3258148209ad9506d09b39',
    messagingSenderId: '372475938876',
    projectId: 'flows-eac79',
    databaseURL: 'https://flows-eac79-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flows-eac79.appspot.com',
  );
}
